// Dados de marcas e modelos de sneakers para seletores

export interface BrandOption {
  value: string;
  label: string;
}

export interface ModelOption {
  value: string;
  label: string;
}

export const TENIS_BRANDS: BrandOption[] = [
  { value: "nike", label: "Nike" },
  { value: "jordan", label: "Jordan" },
  { value: "adidas", label: "Adidas" },
  { value: "new-balance", label: "New Balance" },
  { value: "yeezy", label: "Yeezy" },
  { value: "puma", label: "Puma" },
  { value: "asics", label: "Asics" },
  { value: "reebok", label: "Reebok" },
  { value: "converse", label: "Converse" },
  { value: "vans", label: "Vans" },
  { value: "under-armour", label: "Under Armour" },
  { value: "salomon", label: "Salomon" },
  { value: "balenciaga", label: "Balenciaga" },
  { value: "gucci", label: "Gucci" },
  { value: "louis-vuitton", label: "Louis Vuitton" },
  { value: "off-white", label: "Off-White" },
  { value: "fear-of-god", label: "Fear of God" },
  { value: "other", label: "Outro" },
];

// Alias for backward compatibility
export const SNEAKER_BRANDS = TENIS_BRANDS;

export const MODELS_BY_BRAND: Record<string, ModelOption[]> = {
  nike: [
    { value: "air-force-1", label: "Air Force 1" },
    { value: "air-force-1-low", label: "Air Force 1 Low" },
    { value: "air-force-1-mid", label: "Air Force 1 Mid" },
    { value: "air-force-1-high", label: "Air Force 1 High" },
    { value: "air-max-1", label: "Air Max 1" },
    { value: "air-max-90", label: "Air Max 90" },
    { value: "air-max-95", label: "Air Max 95" },
    { value: "air-max-97", label: "Air Max 97" },
    { value: "air-max-plus", label: "Air Max Plus (TN)" },
    { value: "air-max-270", label: "Air Max 270" },
    { value: "air-max-720", label: "Air Max 720" },
    { value: "air-max-dn", label: "Air Max Dn" },
    { value: "air-max-sndr", label: "Air Max SNDR" },
    { value: "air-max-scorpion", label: "Air Max Scorpion" },
    { value: "air-max-1-86", label: "Air Max 1 '86" },
    { value: "air-rift", label: "Air Rift" },
    { value: "air-huarache", label: "Air Huarache" },
    { value: "air-presto", label: "Air Presto" },
    { value: "air-zoom-alphafly", label: "Air Zoom Alphafly" },
    { value: "dunk-low", label: "Dunk Low" },
    { value: "dunk-high", label: "Dunk High" },
    { value: "sb-dunk-low", label: "SB Dunk Low" },
    { value: "sb-dunk-high", label: "SB Dunk High" },
    { value: "field-general-82", label: "Field General '82" },
    { value: "blazer-mid", label: "Blazer Mid" },
    { value: "blazer-low", label: "Blazer Low" },
    { value: "cortez", label: "Cortez" },
    { value: "vapormax", label: "VaporMax" },
    { value: "vapormax-plus", label: "VaporMax Plus" },
    { value: "zoom-vomero", label: "Zoom Vomero" },
    { value: "zoom-vomero-5", label: "Zoom Vomero 5" },
    { value: "vomero-roam", label: "Vomero Roam" },
    { value: "pegasus", label: "Pegasus" },
    { value: "pegasus-41", label: "Pegasus 41" },
    { value: "pegasus-42", label: "Pegasus 42" },
    { value: "shox", label: "Shox" },
    { value: "shox-r4", label: "Shox R4" },
    { value: "shox-tl", label: "Shox TL" },
    { value: "killshot", label: "Killshot" },
    { value: "waffle-one", label: "Waffle One" },
    { value: "v2k-run", label: "V2K Run" },
    { value: "initiator", label: "Initiator" },
    { value: "p-6000", label: "P-6000" },
    { value: "calm-slide", label: "Calm Slide" },
    { value: "calm-mule", label: "Calm Mule" },
    { value: "acg-mountain-fly", label: "ACG Mountain Fly" },
    { value: "react-element", label: "React Element" },
    { value: "free-run", label: "Free Run" },
    { value: "metcon", label: "Metcon" },
    { value: "book-1", label: "Book 1" },
    { value: "book-2", label: "Book 2" },
    { value: "kobe", label: "Kobe" },
    { value: "kobe-8-protro", label: "Kobe 8 Protro" },
    { value: "kobe-5-protro", label: "Kobe 5 Protro" },
    { value: "lebron", label: "LeBron" },
    { value: "lebron-22", label: "LeBron 22" },
    { value: "kyrie", label: "Kyrie" },
    { value: "kd", label: "KD" },
    { value: "kd-17", label: "KD 17" },
    { value: "ja-1", label: "Ja 1" },
    { value: "ja-2", label: "Ja 2" },
    { value: "gt-cut", label: "GT Cut" },
    { value: "gt-cut-3", label: "GT Cut 3" },
    { value: "sabrina-1", label: "Sabrina 1" },
    { value: "sabrina-2", label: "Sabrina 2" },
    { value: "nike-zoom-gt-hustle", label: "Zoom GT Hustle" },
    { value: "other", label: "Outro" },
  ],
  jordan: [
    { value: "air-jordan-1-low", label: "Air Jordan 1 Low" },
    { value: "air-jordan-1-mid", label: "Air Jordan 1 Mid" },
    { value: "air-jordan-1-high", label: "Air Jordan 1 High OG" },
    { value: "air-jordan-1-low-85", label: "Air Jordan 1 Low '85" },
    { value: "air-jordan-1-high-85", label: "Air Jordan 1 High '85" },
    { value: "air-jordan-1-reimagined", label: "Air Jordan 1 Reimagined" },
    { value: "air-jordan-2", label: "Air Jordan 2" },
    { value: "air-jordan-2-low", label: "Air Jordan 2 Low" },
    { value: "air-jordan-3", label: "Air Jordan 3" },
    { value: "air-jordan-3-reimagined", label: "Air Jordan 3 Reimagined" },
    { value: "air-jordan-4", label: "Air Jordan 4" },
    { value: "air-jordan-4-rm", label: "Air Jordan 4 RM" },
    { value: "air-jordan-4-thunder", label: "Air Jordan 4 Thunder" },
    { value: "air-jordan-4-reimagined", label: "Air Jordan 4 Reimagined" },
    { value: "air-jordan-5", label: "Air Jordan 5" },
    { value: "air-jordan-5-low", label: "Air Jordan 5 Low" },
    { value: "air-jordan-5-burgundy", label: "Air Jordan 5 Burgundy" },
    { value: "air-jordan-6", label: "Air Jordan 6" },
    { value: "air-jordan-7", label: "Air Jordan 7" },
    { value: "air-jordan-8", label: "Air Jordan 8" },
    { value: "air-jordan-9", label: "Air Jordan 9" },
    { value: "air-jordan-10", label: "Air Jordan 10" },
    { value: "air-jordan-11", label: "Air Jordan 11" },
    { value: "air-jordan-11-low", label: "Air Jordan 11 Low" },
    { value: "air-jordan-11-gratitude", label: "Air Jordan 11 Gratitude" },
    { value: "air-jordan-12", label: "Air Jordan 12" },
    { value: "air-jordan-12-low", label: "Air Jordan 12 Low" },
    { value: "air-jordan-13", label: "Air Jordan 13" },
    { value: "air-jordan-13-low", label: "Air Jordan 13 Low" },
    { value: "air-jordan-14", label: "Air Jordan 14" },
    { value: "air-jordan-36", label: "Air Jordan 36" },
    { value: "air-jordan-37", label: "Air Jordan 37" },
    { value: "air-jordan-38", label: "Air Jordan 38" },
    { value: "air-jordan-39", label: "Air Jordan 39" },
    { value: "air-jordan-40", label: "Air Jordan 40" },
    { value: "jordan-travis-scott", label: "Jordan x Travis Scott" },
    { value: "jordan-off-white", label: "Jordan x Off-White" },
    { value: "jordan-union", label: "Jordan x Union" },
    { value: "jordan-dior", label: "Jordan x Dior" },
    { value: "jordan-a-ma-maniere", label: "Jordan x A Ma Maniére" },
    { value: "jordan-fragment", label: "Jordan x Fragment" },
    { value: "jordan-psg", label: "Jordan x PSG" },
    { value: "jordan-trophy-room", label: "Jordan x Trophy Room" },
    { value: "jordan-luka", label: "Jordan Luka" },
    { value: "jordan-luka-3", label: "Jordan Luka 3" },
    { value: "jordan-tatum", label: "Jordan Tatum" },
    { value: "jordan-tatum-3", label: "Jordan Tatum 3" },
    { value: "jordan-zion", label: "Jordan Zion" },
    { value: "jordan-zion-4", label: "Jordan Zion 4" },
    { value: "jordan-why-not", label: "Jordan Why Not" },
    { value: "jordan-spizike", label: "Jordan Spizike" },
    { value: "jordan-ma2", label: "Jordan MA2" },
    { value: "jordan-stadium-90", label: "Jordan Stadium 90" },
    { value: "other", label: "Outro" },
  ],
  adidas: [
    { value: "superstar", label: "Superstar" },
    { value: "stan-smith", label: "Stan Smith" },
    { value: "gazelle", label: "Gazelle" },
    { value: "gazelle-bold", label: "Gazelle Bold" },
    { value: "gazelle-indoor", label: "Gazelle Indoor" },
    { value: "samba", label: "Samba" },
    { value: "samba-og", label: "Samba OG" },
    { value: "samba-adv", label: "Samba ADV" },
    { value: "samba-xl", label: "Samba XLG" },
    { value: "sambae", label: "Sambae" },
    { value: "campus", label: "Campus" },
    { value: "campus-00s", label: "Campus 00s" },
    { value: "handball-spezial", label: "Handball Spezial" },
    { value: "taekwondo", label: "Taekwondo" },
    { value: "sl-72", label: "SL 72" },
    { value: "sl-72-og", label: "SL 72 OG" },
    { value: "sl-76", label: "SL 76" },
    { value: "country", label: "Country" },
    { value: "gt-ii", label: "GT II" },
    { value: "adi2000", label: "Adi2000" },
    { value: "forum-low", label: "Forum Low" },
    { value: "forum-mid", label: "Forum Mid" },
    { value: "forum-high", label: "Forum High" },
    { value: "rivalry-low", label: "Rivalry Low" },
    { value: "rivalry-high", label: "Rivalry High" },
    { value: "ultraboost", label: "Ultraboost" },
    { value: "ultraboost-light", label: "Ultraboost Light" },
    { value: "ultraboost-5", label: "Ultraboost 5" },
    { value: "nmd-r1", label: "NMD R1" },
    { value: "nmd-s1", label: "NMD S1" },
    { value: "nmd-v3", label: "NMD V3" },
    { value: "ozweego", label: "Ozweego" },
    { value: "ozelia", label: "Ozelia" },
    { value: "response-cl", label: "Response CL" },
    { value: "retropy", label: "Retropy" },
    { value: "zx-1000", label: "ZX 1000" },
    { value: "zx-2k", label: "ZX 2K" },
    { value: "zx-8000", label: "ZX 8000" },
    { value: "4dfwd", label: "4DFWD" },
    { value: "ae-1", label: "AE 1" },
    { value: "ae-1-low", label: "AE 1 Low" },
    { value: "harden-8", label: "Harden Vol. 8" },
    { value: "crazy-1", label: "Crazy 1" },
    { value: "crazy-8", label: "Crazy 8" },
    { value: "adilette", label: "Adilette" },
    { value: "adilette-22", label: "Adilette 22" },
    { value: "adifom", label: "Adifom" },
    { value: "adizero", label: "Adizero" },
    { value: "wales-bonner", label: "Adidas x Wales Bonner" },
    { value: "bad-bunny", label: "Adidas x Bad Bunny" },
    { value: "sean-wotherspoon", label: "Adidas x Sean Wotherspoon" },
    { value: "fear-of-god", label: "Adidas x Fear of God Athletics" },
    { value: "other", label: "Outro" },
  ],
  yeezy: [
    { value: "yeezy-350-v1", label: "Yeezy Boost 350 V1" },
    { value: "yeezy-350-v2", label: "Yeezy Boost 350 V2" },
    { value: "yeezy-380", label: "Yeezy Boost 380" },
    { value: "yeezy-450", label: "Yeezy 450" },
    { value: "yeezy-500", label: "Yeezy 500" },
    { value: "yeezy-500-high", label: "Yeezy 500 High" },
    { value: "yeezy-700", label: "Yeezy Boost 700" },
    { value: "yeezy-700-v2", label: "Yeezy 700 V2" },
    { value: "yeezy-700-v3", label: "Yeezy 700 V3" },
    { value: "yeezy-700-mnvn", label: "Yeezy 700 MNVN" },
    { value: "yeezy-750", label: "Yeezy Boost 750" },
    { value: "yeezy-slide", label: "Yeezy Slide" },
    { value: "yeezy-foam-runner", label: "Yeezy Foam Runner" },
    { value: "yeezy-qntm", label: "Yeezy QNTM" },
    { value: "yeezy-knit-runner", label: "Yeezy Knit Runner" },
    { value: "yeezy-nsltd-boot", label: "Yeezy NSLTD Boot" },
    { value: "other", label: "Outro" },
  ],
  "new-balance": [
    { value: "nb-327", label: "327" },
    { value: "nb-530", label: "530" },
    { value: "nb-550", label: "550" },
    { value: "nb-574", label: "574" },
    { value: "nb-580", label: "580" },
    { value: "nb-650", label: "650" },
    { value: "nb-860", label: "860" },
    { value: "nb-990v3", label: "990v3" },
    { value: "nb-990v4", label: "990v4" },
    { value: "nb-990v5", label: "990v5" },
    { value: "nb-990v6", label: "990v6" },
    { value: "nb-991", label: "991" },
    { value: "nb-992", label: "992" },
    { value: "nb-993", label: "993" },
    { value: "nb-997", label: "997" },
    { value: "nb-997h", label: "997H" },
    { value: "nb-998", label: "998" },
    { value: "nb-1000", label: "1000" },
    { value: "nb-1080", label: "1080" },
    { value: "nb-1300", label: "1300" },
    { value: "nb-1500", label: "1500" },
    { value: "nb-1906r", label: "1906R" },
    { value: "nb-1906d", label: "1906D" },
    { value: "nb-2002r", label: "2002R" },
    { value: "nb-9060", label: "9060" },
    { value: "nb-10060", label: "10060" },
    { value: "nb-rc30", label: "RC30" },
    { value: "nb-xc-72", label: "XC-72" },
    { value: "nb-wrpd-runner", label: "WRPD Runner" },
    { value: "nb-made-in-uk", label: "Made in UK" },
    { value: "nb-made-in-usa", label: "Made in USA" },
    { value: "nb-auralee", label: "New Balance x Auralee" },
    { value: "nb-jjjjound", label: "New Balance x JJJJound" },
    { value: "nb-kith", label: "New Balance x Kith" },
    { value: "nb-aime-leon-dore", label: "New Balance x Aimé Leon Dore" },
    { value: "nb-teddy-santis", label: "New Balance x Teddy Santis" },
    { value: "nb-joe-freshgoods", label: "New Balance x Joe Freshgoods" },
    { value: "nb-salehe-bembury", label: "New Balance x Salehe Bembury" },
    { value: "nb-action-bronson", label: "New Balance x Action Bronson" },
    { value: "other", label: "Outro" },
  ],
  puma: [
    { value: "suede", label: "Suede" },
    { value: "suede-xl", label: "Suede XL" },
    { value: "rs-x", label: "RS-X" },
    { value: "rs-xl", label: "RS-XL" },
    { value: "cali", label: "Cali" },
    { value: "palermo", label: "Palermo" },
    { value: "palermo-leather", label: "Palermo Leather" },
    { value: "speedcat", label: "Speedcat" },
    { value: "speedcat-og", label: "Speedcat OG" },
    { value: "speedcat-sparco", label: "Speedcat Sparco" },
    { value: "clyde", label: "Clyde" },
    { value: "slipstream", label: "Slipstream" },
    { value: "slipstream-lo", label: "Slipstream Lo" },
    { value: "mayze", label: "Mayze" },
    { value: "mb-01", label: "MB.01" },
    { value: "mb-02", label: "MB.02" },
    { value: "mb-03", label: "MB.03" },
    { value: "mb-04", label: "MB.04" },
    { value: "scoot-zeros", label: "Scoot Zeros" },
    { value: "scoot-1", label: "Scoot 1" },
    { value: "all-pro-nitro", label: "All Pro Nitro" },
    { value: "rihanna-fenty", label: "Puma x Rihanna Fenty" },
    { value: "other", label: "Outro" },
  ],
  asics: [
    { value: "gel-lyte-iii", label: "Gel-Lyte III" },
    { value: "gel-lyte-iii-cm", label: "Gel-Lyte III CM 2.0" },
    { value: "gel-lyte-v", label: "Gel-Lyte V" },
    { value: "gel-kayano-14", label: "Gel-Kayano 14" },
    { value: "gel-kayano-31", label: "Gel-Kayano 31" },
    { value: "gel-kayano-32", label: "Gel-Kayano 32" },
    { value: "gel-nyc", label: "Gel-NYC" },
    { value: "gel-terrain", label: "Gel-Terrain" },
    { value: "gel-1130", label: "Gel-1130" },
    { value: "gel-1090", label: "Gel-1090" },
    { value: "gel-venture", label: "Gel-Venture" },
    { value: "gel-nimbus", label: "Gel-Nimbus" },
    { value: "gel-nimbus-9", label: "Gel-Nimbus 9" },
    { value: "gel-nimbus-26", label: "Gel-Nimbus 26" },
    { value: "gel-quantum", label: "Gel-Quantum" },
    { value: "gel-quantum-360", label: "Gel-Quantum 360" },
    { value: "gel-sonoma", label: "Gel-Sonoma" },
    { value: "gel-excite", label: "Gel-Excite" },
    { value: "gel-cumulus", label: "Gel-Cumulus" },
    { value: "gt-2160", label: "GT-2160" },
    { value: "gt-2000", label: "GT-2000" },
    { value: "ex89", label: "EX89" },
    { value: "japan-s", label: "Japan S" },
    { value: "skyhand-og", label: "Skyhand OG" },
    { value: "kiko-kostadinov", label: "Asics x Kiko Kostadinov" },
    { value: "vivienne-westwood", label: "Asics x Vivienne Westwood" },
    { value: "cecilie-bahnsen", label: "Asics x Cecilie Bahnsen" },
    { value: "other", label: "Outro" },
  ],
  reebok: [
    { value: "club-c", label: "Club C 85" },
    { value: "club-c-revenge", label: "Club C Revenge" },
    { value: "classic-leather", label: "Classic Leather" },
    { value: "instapump-fury", label: "Instapump Fury" },
    { value: "instapump-fury-95", label: "Instapump Fury 95" },
    { value: "question-mid", label: "Question Mid" },
    { value: "question-low", label: "Question Low" },
    { value: "answer", label: "Answer" },
    { value: "shaq-attaq", label: "Shaq Attaq" },
    { value: "kamikaze", label: "Kamikaze" },
    { value: "zig-kinetica", label: "Zig Kinetica" },
    { value: "nano", label: "Nano" },
    { value: "legacy-lifter", label: "Legacy Lifter" },
    { value: "bb-4000", label: "BB 4000" },
    { value: "dmx", label: "DMX" },
    { value: "aztrek", label: "Aztrek" },
    { value: "other", label: "Outro" },
  ],
  converse: [
    { value: "chuck-70-low", label: "Chuck 70 Low" },
    { value: "chuck-70-high", label: "Chuck 70 High" },
    { value: "chuck-taylor-low", label: "Chuck Taylor All Star Low" },
    { value: "chuck-taylor-high", label: "Chuck Taylor All Star High" },
    { value: "chuck-taylor-platform", label: "Chuck Taylor Platform" },
    { value: "one-star", label: "One Star" },
    { value: "one-star-pro", label: "One Star Pro" },
    { value: "jack-purcell", label: "Jack Purcell" },
    { value: "pro-leather", label: "Pro Leather" },
    { value: "weapon", label: "Weapon" },
    { value: "run-star-hike", label: "Run Star Hike" },
    { value: "run-star-legacy", label: "Run Star Legacy" },
    { value: "run-star-motion", label: "Run Star Motion" },
    { value: "comme-des-garcons", label: "Converse x Comme des Garçons" },
    { value: "off-white", label: "Converse x Off-White" },
    { value: "fear-of-god", label: "Converse x Fear of God" },
    { value: "other", label: "Outro" },
  ],
  vans: [
    { value: "old-skool", label: "Old Skool" },
    { value: "old-skool-platform", label: "Old Skool Platform" },
    { value: "sk8-hi", label: "Sk8-Hi" },
    { value: "sk8-hi-platform", label: "Sk8-Hi Platform" },
    { value: "sk8-low", label: "Sk8-Low" },
    { value: "authentic", label: "Authentic" },
    { value: "era", label: "Era" },
    { value: "slip-on", label: "Slip-On" },
    { value: "half-cab", label: "Half Cab" },
    { value: "style-36", label: "Style 36" },
    { value: "style-73", label: "Style 73" },
    { value: "ultrarange", label: "UltraRange" },
    { value: "knu-skool", label: "Knu Skool" },
    { value: "lampin", label: "Lampin" },
    { value: "bold-ni", label: "Bold Ni" },
    { value: "lowland-cc", label: "Lowland CC" },
    { value: "vault-og", label: "Vault OG" },
    { value: "other", label: "Outro" },
  ],
  "under-armour": [
    { value: "curry-flow", label: "Curry Flow" },
    { value: "curry-11", label: "Curry 11" },
    { value: "curry-12", label: "Curry 12" },
    { value: "hovr", label: "HOVR" },
    { value: "hovr-phantom", label: "HOVR Phantom" },
    { value: "hovr-machina", label: "HOVR Machina" },
    { value: "hovr-infinite", label: "HOVR Infinite" },
    { value: "project-rock", label: "Project Rock" },
    { value: "spawn", label: "Spawn" },
    { value: "clone-magnetic", label: "Clone Magnetic" },
    { value: "charged-rogue", label: "Charged Rogue" },
    { value: "tribase-reign", label: "TriBase Reign" },
    { value: "velociti", label: "Velociti" },
    { value: "slipspeed", label: "SlipSpeed" },
    { value: "other", label: "Outro" },
  ],
  salomon: [
    { value: "xt-6", label: "XT-6" },
    { value: "xt-6-expanse", label: "XT-6 Expanse" },
    { value: "xt-4", label: "XT-4" },
    { value: "xt-wings", label: "XT-Wings 2" },
    { value: "acs-pro", label: "ACS Pro" },
    { value: "acs-pro-advanced", label: "ACS Pro Advanced" },
    { value: "speedcross", label: "Speedcross" },
    { value: "speedcross-6", label: "Speedcross 6" },
    { value: "xt-slate", label: "XT-Slate" },
    { value: "rx-slide", label: "RX Slide" },
    { value: "rx-moc", label: "RX MOC" },
    { value: "s-lab", label: "S/Lab" },
    { value: "ultra-glide", label: "Ultra Glide" },
    { value: "xa-pro", label: "XA Pro 3D" },
    { value: "cross-hike", label: "Cross Hike" },
    { value: "mm6", label: "Salomon x MM6" },
    { value: "comme-des-garcons", label: "Salomon x Comme des Garçons" },
    { value: "other", label: "Outro" },
  ],
  balenciaga: [
    { value: "track", label: "Track" },
    { value: "track-2", label: "Track 2" },
    { value: "track-3", label: "Track 3" },
    { value: "triple-s", label: "Triple S" },
    { value: "speed-trainer", label: "Speed Trainer" },
    { value: "speed-2", label: "Speed 2.0" },
    { value: "defender", label: "Defender" },
    { value: "runner", label: "Runner" },
    { value: "3xl", label: "3XL" },
    { value: "bouncer", label: "Bouncer" },
    { value: "phantom", label: "Phantom" },
    { value: "steroid", label: "Steroid" },
    { value: "sock-runner", label: "Sock Runner" },
    { value: "arena", label: "Arena" },
    { value: "paris", label: "Paris" },
    { value: "other", label: "Outro" },
  ],
  gucci: [
    { value: "rhyton", label: "Rhyton" },
    { value: "ace", label: "Ace" },
    { value: "screener", label: "Screener" },
    { value: "tennis-1977", label: "Tennis 1977" },
    { value: "run", label: "Run" },
    { value: "ultrapace", label: "Ultrapace" },
    { value: "flashtrek", label: "Flashtrek" },
    { value: "basket", label: "Basket" },
    { value: "slide", label: "Slide" },
    { value: "mac80", label: "MAC80" },
    { value: "gazelle", label: "Gucci x Adidas Gazelle" },
    { value: "ogg", label: "OGG" },
    { value: "interlocking-g", label: "Interlocking G" },
    { value: "other", label: "Outro" },
  ],
  "louis-vuitton": [
    { value: "lv-trainer", label: "LV Trainer" },
    { value: "lv-trainer-2", label: "LV Trainer 2" },
    { value: "lv-skate", label: "LV Skate" },
    { value: "lv-archlight", label: "Archlight" },
    { value: "lv-archlight-2", label: "Archlight 2.0" },
    { value: "lv-run-away", label: "Run Away" },
    { value: "lv-frontrow", label: "Frontrow" },
    { value: "lv-ollie", label: "Ollie" },
    { value: "lv-beverly-hills", label: "Beverly Hills" },
    { value: "lv-rivoli", label: "Rivoli" },
    { value: "lv-time-out", label: "Time Out" },
    { value: "lv-stellar", label: "Stellar" },
    { value: "lv-charlie", label: "Charlie" },
    { value: "lv-millenium", label: "Millennium" },
    { value: "lv-af1", label: "LV x Nike Air Force 1" },
    { value: "other", label: "Outro" },
  ],
  "off-white": [
    { value: "out-of-office", label: "Out of Office" },
    { value: "out-of-office-slim", label: "Out of Office Slim" },
    { value: "odsy-1000", label: "Odsy-1000" },
    { value: "odsy-2000", label: "Odsy-2000" },
    { value: "vulc", label: "Vulcanized" },
    { value: "vulc-low", label: "Vulcanized Low" },
    { value: "3-0", label: "3.0" },
    { value: "arrow", label: "Arrow" },
    { value: "kick-off", label: "Kick Off" },
    { value: "sponge", label: "Sponge" },
    { value: "glove-slip-on", label: "Glove Slip On" },
    { value: "floating-arrow", label: "Floating Arrow" },
    { value: "other", label: "Outro" },
  ],
  "fear-of-god": [
    { value: "essentials", label: "Essentials" },
    { value: "essentials-runner", label: "Essentials Runner" },
    { value: "essentials-tennis", label: "Essentials Tennis" },
    { value: "athletics", label: "Athletics" },
    { value: "athletics-1", label: "Athletics 1" },
    { value: "aerobic-low", label: "Aerobic Low" },
    { value: "distance", label: "Distance" },
    { value: "rivalry", label: "Rivalry" },
    { value: "boat-race", label: "Boat Race" },
    { value: "backless", label: "Backless" },
    { value: "hiker", label: "Hiker" },
    { value: "moc", label: "MOC" },
    { value: "fog-x-adidas", label: "Fear of God x Adidas" },
    { value: "other", label: "Outro" },
  ],
};

export function getModelsForBrand(brandValue: string): ModelOption[] {
  if (brandValue === "other" || !brandValue) {
    return [{ value: "other", label: "Outro" }];
  }
  return MODELS_BY_BRAND[brandValue] || [{ value: "other", label: "Outro" }];
}

export function getBrandLabel(value: string): string {
  const brand = TENIS_BRANDS.find((b) => b.value === value);
  return brand?.label || value;
}

export function getModelLabel(brandValue: string, modelValue: string): string {
  const models = getModelsForBrand(brandValue);
  const model = models.find((m) => m.value === modelValue);
  return model?.label || modelValue;
}

// Encontrar a key da marca a partir do label
export function findBrandKey(brandLabel: string | null | undefined): string {
  if (!brandLabel) return "";
  const normalizedLabel = brandLabel.toLowerCase().trim();
  const brand = TENIS_BRANDS.find(
    (b) => b.label.toLowerCase() === normalizedLabel || b.value === normalizedLabel
  );
  return brand?.value || "other";
}

// Encontrar a key do modelo a partir do label e marca
export function findModelKey(brandKey: string, modelLabel: string | null | undefined): string {
  if (!modelLabel || !brandKey) return "";
  const models = getModelsForBrand(brandKey);
  const normalizedLabel = modelLabel.toLowerCase().trim();
  const model = models.find(
    (m) => m.label.toLowerCase() === normalizedLabel || m.value === normalizedLabel
  );
  return model?.value || "other";
}
