import{createClient}from"https://esm.sh/@supabase/supabase-js@2";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, OPTIONS"};
const j=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...H,"Content-Type":"application/json"}});
const sc=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const gm=async(sb:any,cpf:string)=>{const{data}=await sb.from("vault_members").select("id").eq("client_cpf",cpf).single();return data;};
const gs=async(sb:any,mid:string)=>{const{data}=await sb.from("vault_seller_profiles").select("*").eq("member_id",mid).maybeSingle();return data;};
const nt=async(sb:any,t:string,m:string,cpf:string,rid?:string,rt?:string)=>{try{await sb.from("notifications").insert({title:t,message:m,target:"client",target_client_cpf:cpf,type:"info",reference_id:rid||null,reference_type:rt||"marketplace"});}catch(_){}};
const ge=async(sb:any,cpf:string)=>{const{data}=await sb.from("vault_members").select("client_name,client_email,client_phone").eq("client_cpf",cpf).maybeSingle();if(!data?.client_email)return null;return{name:data.client_name,email:data.client_email,phone:data.client_phone||undefined};};
const em=(type:string,data:Record<string,any>)=>{try{const u=Deno.env.get("SUPABASE_URL"),k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(u&&k)fetch(`${u}/functions/v1/send-marketplace-email`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${k}`},body:JSON.stringify({type,...data})}).catch(()=>{});}catch(_){}};
const wa=(type:string,data:Record<string,any>)=>{try{const u=Deno.env.get("SUPABASE_URL"),k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(u&&k)fetch(`${u}/functions/v1/send-whatsapp`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${k}`},body:JSON.stringify({message_type:type,...data})}).catch(()=>{});}catch(_){}};
Deno.serve(async(req)=>{
if(req.method==="OPTIONS")return new Response(null,{headers:H});
const sb=sc(),url=new URL(req.url),a=url.searchParams.get("action"),mt=req.method;
let cpf="visitor";const ah=req.headers.get("authorization");
if(ah?.startsWith("Bearer ")){const{data:u}=await sb.auth.getUser(ah.replace("Bearer ",""));if(u?.user){const{data:p}=await sb.from("client_profiles").select("cpf").eq("user_id",u.user.id).single();if(p?.cpf)cpf=p.cpf;}}
if(cpf==="visitor")return j({error:"Auth required"},401);
try{
if(mt==="POST"&&a==="create-coupon"){const b=await req.json();const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");if(!b.code||!b.discount_value)throw new Error("code e discount_value obrigatórios");const{data:c,error}=await sb.from("marketplace_coupons").insert({seller_id:sl.id,code:b.code.toUpperCase().trim(),discount_type:b.discount_type||"percent",discount_value:b.discount_value,min_purchase:b.min_purchase||0,max_uses:b.max_uses||null,valid_until:b.valid_until||null,listing_ids:b.listing_ids||null}).select().single();if(error)throw error;return j({success:true,coupon:c});}
if(mt==="GET"&&a==="my-coupons"){const mb=await gm(sb,cpf);if(!mb)return j({coupons:[]});const sl=await gs(sb,mb.id);if(!sl)return j({coupons:[]});const{data}=await sb.from("marketplace_coupons").select("*").eq("seller_id",sl.id).order("created_at",{ascending:false});return j({coupons:data||[]});}
if(mt==="PUT"&&a==="update-coupon"){const b=await req.json();const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");await sb.from("marketplace_coupons").update({is_active:b.is_active,max_uses:b.max_uses,valid_until:b.valid_until,discount_value:b.discount_value,min_purchase:b.min_purchase}).eq("id",b.coupon_id).eq("seller_id",sl.id);return j({success:true});}
if(mt==="DELETE"&&a==="delete-coupon"){const id=url.searchParams.get("id");if(!id)throw new Error("ID obrigatório");const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");await sb.from("marketplace_coupons").delete().eq("id",id).eq("seller_id",sl.id);return j({success:true});}
if(mt==="POST"&&a==="validate-coupon"){const b=await req.json();if(!b.code||!b.listing_id)throw new Error("code e listing_id obrigatórios");const{data:li}=await sb.from("vault_marketplace_listings").select("seller_id,price").eq("id",b.listing_id).single();if(!li)throw new Error("Anúncio não encontrado");const{data:c}=await sb.from("marketplace_coupons").select("*").eq("seller_id",li.seller_id).eq("code",b.code.toUpperCase().trim()).eq("is_active",true).maybeSingle();if(!c)return j({valid:false,reason:"Cupom não encontrado"});if(c.valid_until&&new Date(c.valid_until)<new Date())return j({valid:false,reason:"Cupom expirado"});if(c.max_uses&&c.uses_count>=c.max_uses)return j({valid:false,reason:"Cupom esgotado"});if(c.min_purchase&&li.price<c.min_purchase)return j({valid:false,reason:`Compra mínima: R$ ${c.min_purchase}`});if(c.listing_ids&&c.listing_ids.length>0&&!c.listing_ids.includes(b.listing_id))return j({valid:false,reason:"Cupom não válido para este anúncio"});const disc=c.discount_type==="percent"?Math.round(li.price*c.discount_value/100):c.discount_value;return j({valid:true,coupon_id:c.id,discount:disc,discount_type:c.discount_type,discount_value:c.discount_value,final_price:Math.max(0,li.price-disc)});}
if(mt==="POST"&&a==="use-coupon"){const b=await req.json();if(!b.coupon_id)throw new Error("coupon_id obrigatório");const{data:c}=await sb.from("marketplace_coupons").select("uses_count").eq("id",b.coupon_id).single();if(c)await sb.from("marketplace_coupons").update({uses_count:(c.uses_count||0)+1}).eq("id",b.coupon_id);return j({success:true});}
if(mt==="POST"&&a==="boost-activate"){const b=await req.json();if(!b.offer_id)throw new Error("offer_id obrigatório");const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");const{data:plan}=await sb.from("marketplace_plans").select("boost_slots").eq("id",sl.plan_id||"free").single();const mx=plan?.boost_slots||1;const{data:ab}=await sb.from("marketplace_offers").select("id").eq("seller_id",sl.id).not("boost_level","is",null).gt("boost_active_until",new Date().toISOString());if((ab?.length||0)>=mx)throw new Error(`Limite de ${mx} boost(s) atingido.`);const bu=new Date();bu.setDate(bu.getDate()+7);const bl=sl.plan_id==="elite"?"premium":sl.plan_id==="pro"?"standard":"basic";await sb.from("marketplace_offers").update({boost_level:bl,boost_active_until:bu.toISOString()}).eq("id",b.offer_id).eq("seller_id",sl.id);const{data:of2}=await sb.from("marketplace_offers").select("listing_id").eq("id",b.offer_id).single();if(of2?.listing_id)await sb.from("vault_marketplace_listings").update({pro_recommendation:"boosted"}).eq("id",of2.listing_id);return j({success:true,boost_level:bl,boost_until:bu.toISOString()});}
if(mt==="POST"&&a==="boost-deactivate"){const b=await req.json();const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");await sb.from("marketplace_offers").update({boost_level:null,boost_active_until:null}).eq("id",b.offer_id).eq("seller_id",sl.id);return j({success:true});}
if(mt==="GET"&&a==="my-boosts"){const mb=await gm(sb,cpf);if(!mb)return j({boosts:[],max_slots:1});const sl=await gs(sb,mb.id);if(!sl)return j({boosts:[],max_slots:1});const{data:plan}=await sb.from("marketplace_plans").select("boost_slots").eq("id",sl.plan_id||"free").single();const{data:boosts}=await sb.from("marketplace_offers").select("id,boost_level,boost_active_until,product_id,size,price").eq("seller_id",sl.id).not("boost_level","is",null).gt("boost_active_until",new Date().toISOString());return j({boosts:boosts||[],max_slots:plan?.boost_slots||1,used:boosts?.length||0});}
if(mt==="PUT"&&a==="update-storefront"){const b=await req.json();const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");const ud:any={};if(b.bio!==undefined)ud.bio=b.bio;if(b.banner!==undefined)ud.storefront_banner=b.banner;if(b.tagline!==undefined)ud.storefront_tagline=b.tagline;if(b.theme!==undefined)ud.storefront_theme=b.theme;if(b.avatar_url!==undefined)ud.avatar_url=b.avatar_url;await sb.from("vault_seller_profiles").update(ud).eq("id",sl.id);return j({success:true});}
if(mt==="GET"&&a==="my-storefront"){const mb=await gm(sb,cpf);if(!mb)return j({storefront:null});const sl=await gs(sb,mb.id);if(!sl)return j({storefront:null});return j({storefront:{bio:sl.bio,banner:sl.storefront_banner,tagline:sl.storefront_tagline,theme:sl.storefront_theme,avatar_url:sl.avatar_url,seller_id:sl.id}});}
if(mt==="PUT"&&a==="review-kyc"){const b=await req.json();if(!b.seller_id||!b.decision)throw new Error("seller_id e decision obrigatórios");const ud:any={kyc_status:b.decision,kyc_reviewed_at:new Date().toISOString(),kyc_reviewed_by:cpf};if(b.decision==="rejected"&&b.reason)ud.kyc_rejection_reason=b.reason;await sb.from("vault_seller_profiles").update(ud).eq("id",b.seller_id);const{data:sl}=await sb.from("vault_seller_profiles").select("member:vault_members!inner(client_cpf,client_name,client_email,client_phone)").eq("id",b.seller_id).single();if(sl?.member){const et=b.decision==="approved"?"mk_kyc_approved":"mk_kyc_rejected";const nt2=b.decision==="approved"?"✅ Cadastro aprovado!":"⚠️ Documentos não aprovados";const nm=b.decision==="approved"?"Parabéns! Você já pode vender.":`Documentos não aprovados. ${b.reason||""}`;await nt(sb,nt2,nm,sl.member.client_cpf,b.seller_id,"marketplace_kyc");if(sl.member.client_email)em(et,{recipient_name:sl.member.client_name,recipient_email:sl.member.client_email,kyc_rejection_reason:b.reason||null});if(sl.member.client_phone)wa(et,{recipient_phone:sl.member.client_phone,recipient_name:sl.member.client_name,kyc_rejection_reason:b.reason||null});}return j({success:true});}
if(mt==="POST"&&a==="snapshot-prices"){const{data:ps}=await sb.from("marketplace_products").select("id").eq("is_active",true).gt("total_offers",0);let cnt=0;for(const p of(ps||[])){const{data:os}=await sb.from("marketplace_offers").select("price").eq("product_id",p.id).eq("status","active");if(!os||!os.length)continue;const prices=os.map((o:any)=>o.price);await sb.from("marketplace_price_history").upsert({product_id:p.id,recorded_date:new Date().toISOString().split("T")[0],min_price:Math.min(...prices),avg_price:Math.round(prices.reduce((a:number,b:number)=>a+b,0)/prices.length),max_price:Math.max(...prices),offers_count:os.length},{onConflict:"product_id,recorded_date"});cnt++;}return j({success:true,products_snapshotted:cnt});}
return j({error:"Ação não encontrada"},404);
}catch(e:any){console.error("mkv2-store error:",e);return j({error:e.message},500);}
});