import{createClient}from"https://esm.sh/@supabase/supabase-js@2";
import{resolveAuthCpf}from"../_shared/mk-helpers.ts";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, OPTIONS"};
const j=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...H,"Content-Type":"application/json"}});
const sc=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const gm=async(sb:any,cpf:string)=>{const{data}=await sb.from("vault_members").select("id").eq("client_cpf",cpf).single();return data;};
const gs=async(sb:any,mid:string)=>{const{data}=await sb.from("vault_seller_profiles").select("*").eq("member_id",mid).maybeSingle();return data;};
const nt=async(sb:any,t:string,m:string,cpf:string,rid?:string,rt?:string)=>{try{await sb.from("notifications").insert({title:t,message:m,target:"client",target_client_cpf:cpf,type:"info",reference_id:rid||null,reference_type:rt||"marketplace"});}catch(_){}};
Deno.serve(async(req)=>{
if(req.method==="OPTIONS")return new Response(null,{headers:H});
const sb=sc(),url=new URL(req.url),a=url.searchParams.get("action"),mt=req.method;
let cpf="visitor";const ah=req.headers.get("authorization");
if(ah?.startsWith("Bearer ")){const{data:u}=await sb.auth.getUser(ah.replace("Bearer ",""));if(u?.user){const{data:p}=await sb.from("client_profiles").select("cpf").eq("user_id",u.user.id).single();if(p?.cpf)cpf=p.cpf;}}
if(cpf==="visitor")return j({error:"Auth required"},401);
try{
if(mt==="GET"&&a==="my-collections"){const mb=await gm(sb,cpf);if(!mb)return j({collections:[]});const sl=await gs(sb,mb.id);if(!sl)return j({collections:[]});const{data}=await sb.from("seller_collections").select("*").eq("seller_id",sl.id).order("sort_order",{ascending:true});return j({collections:data||[]});}
if(mt==="POST"&&a==="create-collection"){const b=await req.json();const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");if(sl.plan_id!=="elite")throw new Error("Coleções apenas no plano Elite.");const{data,error}=await sb.from("seller_collections").insert({seller_id:sl.id,name:b.name,description:b.description||null,cover_image:b.cover_image||null,listing_ids:b.listing_ids||[]}).select().single();if(error)throw error;return j({collection:data});}
if(mt==="PUT"&&a==="update-collection"){const b=await req.json();const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");await sb.from("seller_collections").update({name:b.name,description:b.description,cover_image:b.cover_image,listing_ids:b.listing_ids,is_active:b.is_active,updated_at:new Date().toISOString()}).eq("id",b.id).eq("seller_id",sl.id);return j({success:true});}
if(mt==="DELETE"&&a==="delete-collection"){const id=url.searchParams.get("id");if(!id)throw new Error("ID obrigatório");const mb=await gm(sb,cpf);if(!mb)throw new Error("Membro não encontrado");const sl=await gs(sb,mb.id);if(!sl)throw new Error("Vendedor não encontrado");await sb.from("seller_collections").delete().eq("id",id).eq("seller_id",sl.id);return j({success:true});}
if(mt==="POST"&&a==="toggle-follow"){const{seller_id}=await req.json();if(!seller_id)throw new Error("seller_id obrigatório");const{data:ex}=await sb.from("marketplace_seller_follows").select("id").eq("follower_cpf",cpf).eq("seller_id",seller_id).maybeSingle();if(ex){await sb.from("marketplace_seller_follows").delete().eq("id",ex.id);return j({following:false});}await sb.from("marketplace_seller_follows").insert({follower_cpf:cpf,seller_id});const{data:sl}=await sb.from("vault_seller_profiles").select("member_id").eq("id",seller_id).maybeSingle();if(sl?.member_id){const{data:mem}=await sb.from("vault_members").select("client_cpf").eq("id",sl.member_id).maybeSingle();if(mem)await nt(sb,"👤 Novo seguidor!","Alguém começou a seguir sua loja!",mem.client_cpf,seller_id,"marketplace_follow");}return j({following:true});}
if(mt==="GET"&&a==="is-following"){const sid=url.searchParams.get("seller_id");if(!sid)return j({following:false});const{data}=await sb.from("marketplace_seller_follows").select("id").eq("follower_cpf",cpf).eq("seller_id",sid).maybeSingle();return j({following:!!data});}
if(mt==="GET"&&a==="my-follows"){const{data}=await sb.from("marketplace_seller_follows").select("seller_id,created_at").eq("follower_cpf",cpf);return j({follows:data||[]});}
if(mt==="GET"&&a==="loyalty-balance"){const{data}=await sb.rpc("get_loyalty_balance",{p_cpf:cpf});const{data:history}=await sb.from("marketplace_loyalty_points").select("*").eq("user_cpf",cpf).order("created_at",{ascending:false}).limit(20);return j({balance:data||0,history:history||[]});}
if(mt==="POST"&&a==="check-badges"){const mb=await gm(sb,cpf);if(!mb)return j({badges:[]});const sl=await gs(sb,mb.id);if(!sl)return j({badges:[]});const{data:ex}=await sb.from("marketplace_seller_badges").select("badge_type").eq("seller_id",sl.id);const hb=(t:string)=>(ex||[]).some((b:any)=>b.badge_type===t);const nb:any[]=[];if(sl.total_sales_count>=1&&!hb("first_sale"))nb.push({seller_id:sl.id,badge_type:"first_sale",badge_name:"Primeira Venda",badge_icon:"🎉"});if(sl.total_sales_count>=10&&!hb("ten_sales"))nb.push({seller_id:sl.id,badge_type:"ten_sales",badge_name:"10 Vendas",badge_icon:"🔥"});if(sl.total_sales_count>=50&&!hb("fifty_sales"))nb.push({seller_id:sl.id,badge_type:"fifty_sales",badge_name:"50 Vendas",badge_icon:"💎"});if(sl.total_sales_count>=5&&(sl.dispute_rate||0)===0&&!hb("zero_disputes"))nb.push({seller_id:sl.id,badge_type:"zero_disputes",badge_name:"Zero Disputas",badge_icon:"🛡️"});if((sl.average_rating||0)>=4.8&&(sl.ratings_count||0)>=5&&!hb("top_rated"))nb.push({seller_id:sl.id,badge_type:"top_rated",badge_name:"Top Avaliado",badge_icon:"⭐"});if(sl.verified_badge&&!hb("verified"))nb.push({seller_id:sl.id,badge_type:"verified",badge_name:"Verificado",badge_icon:"✅"});
  if(nb.length>0){await sb.from("marketplace_seller_badges").insert(nb);const{data:mem}=await sb.from("vault_members").select("client_cpf").eq("id",mb.id).maybeSingle();if(mem){for(const badge of nb)await nt(sb,`🏅 ${badge.badge_name}!`,`Badge "${badge.badge_name}" ${badge.badge_icon} desbloqueado!`,mem.client_cpf,sl.id,"marketplace_badge");}}
  const{data:all}=await sb.from("marketplace_seller_badges").select("*").eq("seller_id",sl.id).order("earned_at",{ascending:false});return j({badges:all||[],new_badges:nb});
}
return j({error:"Ação não encontrada"},404);
}catch(e:any){console.error("mkv2-social error:",e);return j({error:e.message},500);}
});