import{createClient}from"https://esm.sh/@supabase/supabase-js@2";
import{resolveCpf as _rc}from"../_shared/mk-helpers.ts";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, OPTIONS"};
const j=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...H,"Content-Type":"application/json"}});
const sc=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const PUB=new Set(["listings","listing-detail","seller-public-profile"]);
Deno.serve(async(req)=>{
if(req.method==="OPTIONS")return new Response(null,{headers:H});
const sb=sc(),url=new URL(req.url),a=url.searchParams.get("action"),mt=req.method;
const{cpf:_c,errorResponse:_e}=await _rc(req,sb,PUB,a);if(_e)return _e;const cpf=_c!;
try{
if(a==="listings"){
  const pg=+(url.searchParams.get("page")||"1"),lm=20,of2=(pg-1)*lm;const br=url.searchParams.get("brand"),ct=url.searchParams.get("condition"),mn=url.searchParams.get("min_price"),mx=url.searchParams.get("max_price"),sz=url.searchParams.get("size"),sr=url.searchParams.get("search"),so=url.searchParams.get("sort")||"recent";
  let q=sb.from("vault_marketplace_listings").select("*",{count:"exact"}).eq("status","active");
  if(br)q=q.ilike("brand",`%${br}%`);if(ct)q=q.eq("condition",ct);if(mn)q=q.gte("price",+mn);if(mx)q=q.lte("price",+mx);if(sz)q=q.eq("size",sz);if(sr)q=q.or(`title.ilike.%${sr}%,brand.ilike.%${sr}%,model.ilike.%${sr}%`);
  if(so==="price_asc")q=q.order("price",{ascending:true});else if(so==="price_desc")q=q.order("price",{ascending:false});else q=q.order("published_at",{ascending:false});
  q=q.range(of2,of2+lm-1);const{data,count,error}=await q;if(error)throw error;return j({listings:data||[],total:count||0});
}
if(a==="listing-detail"){const id=url.searchParams.get("id");if(!id)throw new Error("id obrigatório");const{data,error}=await sb.from("vault_marketplace_listings").select(`*,seller:vault_seller_profiles!inner(id,plan_id,verified_badge,average_rating,total_sales_count,current_fee_percent,member:vault_members!inner(client_name,tier))`).eq("id",id).single();if(error)throw error;if(data)await sb.from("vault_marketplace_listings").update({views_count:(data.views_count||0)+1}).eq("id",id);return j({listing:data});}
if(a==="my-listings"){const{data,error}=await sb.from("vault_marketplace_listings").select(`*,seller:vault_seller_profiles!inner(member:vault_members!inner(client_cpf))`).eq("seller.member.client_cpf",cpf).order("created_at",{ascending:false});if(error)throw error;return j({listings:data||[]});}
if(mt==="POST"&&a==="create-listing"){const b=await req.json();if(!b.price||b.price<=0||b.price>99999)throw new Error("Preço inválido. Mínimo R$ 1, máximo R$ 99.999");const{data:mb}=await sb.from("vault_members").select("id").eq("client_cpf",cpf).single();if(!mb)throw new Error("Membro não encontrado");let{data:sl}=await sb.from("vault_seller_profiles").select("id,kyc_status,plan_id").eq("member_id",mb.id).maybeSingle();if(!sl){const{data:ns,error:se}=await sb.from("vault_seller_profiles").insert({member_id:mb.id}).select("id,kyc_status,plan_id").single();if(se)throw se;sl=ns;}if(!sl||sl.kyc_status!=="approved")return j({error:"Sua conta precisa ser verificada antes de anunciar. Acesse Minha Loja para enviar seus documentos."},403);
// ── Plan listing limit check ──
const PLAN_DEFAULTS:Record<string,number>={"free":3,"basico":3,"starter":10};
let maxListings:number|null=null;
if(sl.plan_id){const{data:plan}=await sb.from("marketplace_plans").select("max_active_listings,name").eq("id",sl.plan_id).maybeSingle();if(plan){maxListings=plan.max_active_listings;if(maxListings===null||maxListings===undefined){const k=String(plan.name||sl.plan_id).toLowerCase();maxListings=PLAN_DEFAULTS[k]??null;}}}else{maxListings=PLAN_DEFAULTS["free"];}
if(maxListings!==null){const{count:activeCount}=await sb.from("vault_marketplace_listings").select("id",{count:"exact",head:true}).eq("seller_id",sl.id).eq("status","active");const cur=activeCount||0;if(cur>=maxListings)return j({error:"Você atingiu o limite de anúncios do seu plano. Faça upgrade para anunciar mais.",limit:maxListings,current:cur,plan_id:sl.plan_id||"free"},403);}
// ── End plan limit check ──
const sm=b.price>=2000?"bravenza":(b.shipping_mode||"direct");const{data:li,error}=await sb.from("vault_marketplace_listings").insert({seller_id:sl.id,vault_item_id:b.vault_item_id||null,title:b.title,description:b.description||null,brand:b.brand||null,model:b.model||null,size:b.size||null,condition:b.condition||"novo",photos:b.photos||[],price:b.price,original_purchase_price:b.original_purchase_price||null,shipping_mode:sm,shipping_cost_estimate:0,is_vault_certified:!!b.vault_item_id,status:"active",published_at:new Date().toISOString(),product_id:b.product_id||null}).select().single();if(error)throw error;return j({success:true,listing:li});}
if(mt==="PUT"&&a==="update-listing"){const b=await req.json();const{data:li2}=await sb.from("vault_marketplace_listings").select("seller_id").eq("id",b.id).single();if(!li2)throw new Error("Anúncio não encontrado");const{data:sp2}=await sb.from("vault_seller_profiles").select("member:vault_members!inner(client_cpf)").eq("id",li2.seller_id).single();if(!sp2||sp2.member?.client_cpf!==cpf)return j({error:"Acesso negado"},403);const ud:any={};if(b.title)ud.title=b.title;if(b.description!==undefined)ud.description=b.description;if(b.price)ud.price=b.price;if(b.photos)ud.photos=b.photos;if(b.condition)ud.condition=b.condition;if(b.shipping_mode)ud.shipping_mode=b.shipping_mode;if(b.product_id)ud.product_id=b.product_id;const{error}=await sb.from("vault_marketplace_listings").update(ud).eq("id",b.id);if(error)throw error;return j({success:true});}
if(mt==="DELETE"&&a==="delete-listing"){const id=url.searchParams.get("id");if(!id)throw new Error("id obrigatório");const{data:li3}=await sb.from("vault_marketplace_listings").select("seller_id").eq("id",id).single();if(!li3)throw new Error("Anúncio não encontrado");const{data:sp3}=await sb.from("vault_seller_profiles").select("member:vault_members!inner(client_cpf)").eq("id",li3.seller_id).single();if(!sp3||sp3.member?.client_cpf!==cpf)return j({error:"Acesso negado"},403);await sb.from("vault_marketplace_listings").update({status:"deleted"}).eq("id",id);return j({success:true});}
if(mt==="POST"&&a==="toggle-favorite"){const b=await req.json();const{data:ex}=await sb.from("marketplace_favorites").select("id").eq("listing_id",b.listing_id).eq("user_cpf",cpf).maybeSingle();if(ex){await sb.from("marketplace_favorites").delete().eq("id",ex.id);return j({favorited:false});}await sb.from("marketplace_favorites").insert({listing_id:b.listing_id,user_cpf:cpf});return j({favorited:true});}
if(a==="seller-profile"){const{data:mb}=await sb.from("vault_members").select("id").eq("client_cpf",cpf).single();if(!mb)return j({seller:null});const{data:sl}=await sb.from("vault_seller_profiles").select("*").eq("member_id",mb.id).maybeSingle();return j({seller:sl});}
if(a==="seller-public-profile"){const sid=url.searchParams.get("seller_id");if(!sid)throw new Error("seller_id obrigatório");const{data:sl}=await sb.from("vault_seller_profiles").select(`id,plan_id,verified_badge,average_rating,ratings_count,total_sales_count,total_sales_value,tier,bio,storefront_banner,storefront_tagline,storefront_theme,avatar_url,followers_count,member:vault_members!inner(client_name,tier)`).eq("id",sid).single();if(!sl)throw new Error("Vendedor não encontrado");const{data:ls}=await sb.from("vault_marketplace_listings").select("id,title,price,photos,condition,brand,model,size,published_at").eq("seller_id",sid).eq("status","active").order("published_at",{ascending:false}).limit(50);const{data:badges}=await sb.from("marketplace_seller_badges").select("badge_name,badge_icon,badge_type").eq("seller_id",sid);return j({seller:sl,listings:ls||[],badges:badges||[]});}
return j({error:"Ação não encontrada"},404);
}catch(e:any){console.error("mkv2-listings error:",e);return j({error:e.message},500);}
});