-- First, add all new enum values
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'REQUEST_RECEIVED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'BUDGET_SENT';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'DEPOSIT_CONFIRMED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'SEARCH_SELECTION';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PRODUCT_FOUND';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PREPARING_INTERNATIONAL';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'INTERNATIONAL_TRANSIT';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'ARRIVED_BRAZIL';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PRODUCT_INSPECTED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'BALANCE_PENDING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'FULLY_PAID';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'SHIPPED_TO_CLIENT';