import{createClient}from"https://esm.sh/@supabase/supabase-js@2";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, OPTIONS"};
const j=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...H,"Content-Type":"application/json"}});
const sc=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const nt=async(sb:any,t:string,m:string,cpf:string,rid?:string,rt?:string)=>{try{await sb.from("notifications").insert({title:t,message:m,target:"client",target_client_cpf:cpf,type:"info",reference_id:rid||null,reference_type:rt||"marketplace"});}catch(_){}};
const ge=async(sb:any,cpf:string)=>{const{data}=await sb.from("vault_members").select("client_name,client_email,client_phone").eq("client_cpf",cpf).maybeSingle();if(!data?.client_email)return null;return{name:data.client_name,email:data.client_email,phone:data.client_phone||undefined};};
const em=(type:string,data:Record<string,any>)=>{try{const u=Deno.env.get("SUPABASE_URL"),k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(u&&k)fetch(`${u}/functions/v1/send-marketplace-email`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${k}`},body:JSON.stringify({type,...data})}).catch(()=>{});}catch(_){}};
const wa=(type:string,data:Record<string,any>)=>{try{const u=Deno.env.get("SUPABASE_URL"),k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(u&&k)fetch(`${u}/functions/v1/send-whatsapp`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${k}`},body:JSON.stringify({message_type:type,...data})}).catch(()=>{});}catch(_){}};
Deno.serve(async(req)=>{
if(req.method==="OPTIONS")return new Response(null,{headers:H});
const sb=sc(),url=new URL(req.url),a=url.searchParams.get("action"),mt=req.method;
let cpf="visitor";const ah=req.headers.get("authorization");
if(ah?.startsWith("Bearer ")){const{data:u}=await sb.auth.getUser(ah.replace("Bearer ",""));if(u?.user){const{data:p}=await sb.from("client_profiles").select("cpf").eq("user_id",u.user.id).single();if(p?.cpf)cpf=p.cpf;}}
if(cpf==="visitor")return j({error:"Auth required"},401);
try{
if(mt==="POST"&&a==="make-offer"){
  const b=await req.json();const{data:li}=await sb.from("vault_marketplace_listings").select(`id,title,seller:vault_seller_profiles!inner(member:vault_members!inner(client_cpf))`).eq("id",b.listing_id).eq("status","active").single();
  if(!li)throw new Error("Anúncio não encontrado");if(li.seller?.member?.client_cpf===cpf)throw new Error("Não pode ofertar próprio anúncio");
  const{data:of2,error}=await sb.from("vault_marketplace_offers").insert({listing_id:b.listing_id,buyer_cpf:cpf,buyer_name:b.buyer_name||"Comprador",offer_price:b.offer_price,message:b.message||null,bundle_id:b.bundle_id||null,bundle_discount_percent:b.bundle_discount_percent||0}).select().single();if(error)throw error;
  await sb.from("marketplace_negotiation_events").insert({offer_id:of2.id,event_type:"offer_made",actor_cpf:cpf,actor_name:b.buyer_name||"Comprador",price:b.offer_price,message:b.message||null});
  await nt(sb,"💰 Nova oferta!",`R$ ${b.offer_price.toFixed(2)} por "${li.title}".`,li.seller.member.client_cpf,li.id,"marketplace_offer");
  const se=await ge(sb,li.seller.member.client_cpf);if(se){em("mk_offer_received",{recipient_name:se.name,recipient_email:se.email,listing_title:li.title,offer_price:b.offer_price,buyer_name:b.buyer_name||"Comprador"});if(se.phone)wa("mk_offer_received",{recipient_phone:se.phone,recipient_name:se.name,listing_title:li.title,offer_price:b.offer_price,buyer_name:b.buyer_name||"Comprador"});}
  return j({success:true,offer:of2});
}
if(mt==="GET"&&a==="listing-offers"){const lid=url.searchParams.get("listing_id");if(!lid)throw new Error("listing_id obrigatório");const{data,error}=await sb.from("vault_marketplace_offers").select("*").eq("listing_id",lid).order("created_at",{ascending:false});if(error)throw error;return j({offers:data||[]});}
if(mt==="GET"&&a==="my-offers"){const{data,error}=await sb.from("vault_marketplace_offers").select(`*,listing:vault_marketplace_listings!inner(title,photos,price)`).eq("buyer_cpf",cpf).order("created_at",{ascending:false});if(error)throw error;return j({offers:data||[]});}
if(mt==="PUT"&&a==="respond-offer"){
  const b=await req.json();const{data:o}=await sb.from("vault_marketplace_offers").select(`id,listing_id,buyer_cpf,buyer_name,offer_price,listing:vault_marketplace_listings!inner(title)`).eq("id",b.offer_id).single();if(!o)throw new Error("Oferta não encontrada");
  const u:any={responded_at:new Date().toISOString()};
  if(b.response==="accept"){u.status="accepted";await sb.from("marketplace_negotiation_events").insert({offer_id:o.id,event_type:"accepted",actor_cpf:cpf,price:o.offer_price});await nt(sb,"✅ Oferta aceita!",`Oferta por "${o.listing?.title}" aceita!`,o.buyer_cpf,o.listing_id,"marketplace_offer");const be=await ge(sb,o.buyer_cpf);if(be){em("mk_offer_accepted",{recipient_name:be.name,recipient_email:be.email,listing_title:o.listing?.title,offer_price:o.offer_price});if(be.phone)wa("mk_offer_accepted",{recipient_phone:be.phone,recipient_name:be.name,listing_title:o.listing?.title,offer_price:o.offer_price});}}
  else if(b.response==="reject"){u.status="rejected";await sb.from("marketplace_negotiation_events").insert({offer_id:o.id,event_type:"rejected",actor_cpf:cpf,message:b.reason||null});await nt(sb,"❌ Recusada",`Oferta por "${o.listing?.title}" recusada.`,o.buyer_cpf,o.listing_id,"marketplace_offer");const be=await ge(sb,o.buyer_cpf);if(be){em("mk_offer_rejected",{recipient_name:be.name,recipient_email:be.email,listing_title:o.listing?.title,offer_price:o.offer_price,reject_reason:b.reason||""});if(be.phone)wa("mk_offer_rejected",{recipient_phone:be.phone,recipient_name:be.name,listing_title:o.listing?.title,offer_price:o.offer_price});}}
  else if(b.response==="counter"){u.status="counter";u.counter_price=b.counter_price;u.counter_message=b.counter_message||null;u.expires_at=new Date(Date.now()+48*3600000).toISOString();await sb.from("marketplace_negotiation_events").insert({offer_id:o.id,event_type:"counter_sent",actor_cpf:cpf,price:b.counter_price,message:b.counter_message||null});await nt(sb,"🔄 Contra-proposta!",`R$ ${b.counter_price?.toFixed(2)} por "${o.listing?.title}".`,o.buyer_cpf,o.listing_id,"marketplace_offer");const be=await ge(sb,o.buyer_cpf);if(be){em("mk_offer_counter",{recipient_name:be.name,recipient_email:be.email,listing_title:o.listing?.title,offer_price:o.offer_price,counter_price:b.counter_price,counter_message:b.counter_message});if(be.phone)wa("mk_offer_counter",{recipient_phone:be.phone,recipient_name:be.name,listing_title:o.listing?.title,offer_price:o.offer_price,counter_price:b.counter_price});}}
  await sb.from("vault_marketplace_offers").update(u).eq("id",b.offer_id);return j({success:true});
}
if(mt==="PUT"&&a==="accept-counter"){const b=await req.json();const{data:o}=await sb.from("vault_marketplace_offers").select(`id,listing_id,buyer_cpf,counter_price,listing:vault_marketplace_listings!inner(title,seller:vault_seller_profiles!inner(member:vault_members!inner(client_cpf)))`).eq("id",b.offer_id).eq("buyer_cpf",cpf).eq("status","counter").single();if(!o)throw new Error("Contra-proposta não encontrada");await sb.from("vault_marketplace_offers").update({status:"accepted",offer_price:o.counter_price,responded_at:new Date().toISOString()}).eq("id",o.id);await sb.from("marketplace_negotiation_events").insert({offer_id:o.id,event_type:"counter_accepted",actor_cpf:cpf,price:o.counter_price});const sc2=o.listing?.seller?.member?.client_cpf;if(sc2)await nt(sb,"✅ Contra-proposta aceita!",`Comprador aceitou R$ ${o.counter_price?.toFixed(2)} por "${o.listing?.title}".`,sc2,o.listing_id,"marketplace_offer");return j({success:true});}
if(mt==="PUT"&&a==="reject-counter"){const b=await req.json();const{data:o}=await sb.from("vault_marketplace_offers").select(`id,listing_id,buyer_cpf,listing:vault_marketplace_listings!inner(title,seller:vault_seller_profiles!inner(member:vault_members!inner(client_cpf)))`).eq("id",b.offer_id).eq("buyer_cpf",cpf).eq("status","counter").single();if(!o)throw new Error("Contra-proposta não encontrada");await sb.from("vault_marketplace_offers").update({status:"rejected",responded_at:new Date().toISOString()}).eq("id",o.id);await sb.from("marketplace_negotiation_events").insert({offer_id:o.id,event_type:"rejected",actor_cpf:cpf,message:"Comprador recusou contra-proposta"});const sc2=o.listing?.seller?.member?.client_cpf;if(sc2)await nt(sb,"❌ Contra-proposta recusada",`Comprador recusou a contra-proposta por "${o.listing?.title}".`,sc2,o.listing_id,"marketplace_offer");return j({success:true});}
if(mt==="POST"&&a==="bundle-offer"){
  const b=await req.json();const{listing_ids,prices,message:bm,buyer_name,discount_percent}=b;if(!listing_ids||listing_ids.length<2)throw new Error("Bundle requer pelo menos 2 anúncios");
  const{data:ls}=await sb.from("vault_marketplace_listings").select(`id,title,price,seller_id,seller:vault_seller_profiles!inner(member:vault_members!inner(client_cpf))`).in("id",listing_ids).eq("status","active");
  if(!ls||ls.length!==listing_ids.length)throw new Error("Alguns anúncios não encontrados");const sids=[...new Set(ls.map((l:any)=>l.seller_id))];if(sids.length>1)throw new Error("Bundle só permite mesmo vendedor");if(ls[0].seller?.member?.client_cpf===cpf)throw new Error("Não pode ofertar próprios anúncios");
  const bid=crypto.randomUUID();const offers:any[]=[];
  for(let i=0;i<ls.length;i++){const li=ls[i];const op=prices?.[i]||li.price*(1-(discount_percent||0)/100);const{data:of2}=await sb.from("vault_marketplace_offers").insert({listing_id:li.id,buyer_cpf:cpf,buyer_name:buyer_name||"Comprador",offer_price:Math.round(op*100)/100,message:bm||null,bundle_id:bid,bundle_discount_percent:discount_percent||0}).select().single();if(of2){offers.push(of2);await sb.from("marketplace_negotiation_events").insert({offer_id:of2.id,event_type:"offer_made",actor_cpf:cpf,actor_name:buyer_name||"Comprador",price:op,message:`Bundle (${ls.length} itens)`});}}
  const tot=ls.reduce((s:number,l:any)=>s+l.price,0);const totO=offers.reduce((s:number,o:any)=>s+o.offer_price,0);
  await nt(sb,"📦 Bundle offer!",`${offers.length} itens por R$ ${totO.toFixed(2)} (de R$ ${tot.toFixed(2)}).`,ls[0].seller.member.client_cpf,bid,"marketplace_bundle");return j({success:true,bundle_id:bid,offers});
}
if(mt==="GET"&&a==="negotiation-timeline"){const oid=url.searchParams.get("offer_id");if(!oid)throw new Error("offer_id obrigatório");const{data,error}=await sb.from("marketplace_negotiation_events").select("*").eq("offer_id",oid).order("created_at",{ascending:true});if(error)throw error;return j({events:data||[]});}
if(mt==="POST"&&a==="expire-offers"){const count=await sb.rpc("auto_expire_marketplace_offers");return j({success:true,expired_count:count?.data||0});}
return j({error:"Ação não encontrada"},404);
}catch(e:any){console.error("mkv2-offers error:",e);return j({error:e.message},500);}
});